[package]
name = "genanki-rs"
version = "0.4.0"
authors = ["Yannick Funk <yannickfunk@yahoo.de>"]
edition = "2018"
description = "Crate to create decks for the open source flashcard platform Anki. Based on Python library genanki"
license = "MIT"
readme = "README.md"
repository = "https://github.com/yannickfunk/genanki-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["sqlite-bundled"]
sqlite-bundled = ["rusqlite/bundled"]

[dependencies]
rusqlite = "0.37.0"
tempfile = "3.23.0"
zip = "6.0.0"
serde_json = "1.0.145"
fancy-regex = "0.16.2"
serde = { version = "1.0", features = ["derive"] }
ramhorns = "1.0.1"
thiserror = "2.0.17"

[dev-dependencies]
anyhow = "1.0.100"
pyo3 = { version = "0.27.2", features = [ "auto-initialize" ] }
serial_test = "3.2.0"
uuid = { version = "1.19.0", features = [ "v4" ] }
